In [246]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, MinMaxScaler , OneHotEncoder
from sklearn.datasets import load_wine, make_classification , load_diabetes , make_regression
from sklearn.impute import SimpleImputer


## PARTE 1

# Esercizio 1.1 Wine
- Quanti campioni e feature contiene?
- Quante classi ci sono?
- Quali sono i nomi delle feature?
- Visualizza le prime 3 righe dei dati

In [247]:
wine_data = load_wine()

df = pd.DataFrame(wine_data.data, columns=wine_data.feature_names)

print(df.info())
print(df.describe())

print(df.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   alcohol                       178 non-null    float64
 1   malic_acid                    178 non-null    float64
 2   ash                           178 non-null    float64
 3   alcalinity_of_ash             178 non-null    float64
 4   magnesium                     178 non-null    float64
 5   total_phenols                 178 non-null    float64
 6   flavanoids                    178 non-null    float64
 7   nonflavanoid_phenols          178 non-null    float64
 8   proanthocyanins               178 non-null    float64
 9   color_intensity               178 non-null    float64
 10  hue                           178 non-null    float64
 11  od280/od315_of_diluted_wines  178 non-null    float64
 12  proline                       178 non-null    float64
dtypes: fl

In [248]:
# --- Quanti campioni e feature contiene? ---
num_samples, num_features = df.shape
num_features 

print(f"1. Il dataset contiene {num_samples} campioni e {num_features} feature.")
print("-" * 50)

# --- Quante classi ci sono? ---
num_classes = len(wine_data.target_names)
class_names = wine_data.target_names

print(f"2. Ci sono {num_classes} classi nel dataset.")
print("-" * 50)

# --- Quali sono i nomi delle feature? ---
feature_names = wine_data.feature_names

print("3. I nomi delle feature sono:")
for name in feature_names:
    print(f"   - {name}")
print("-" * 50)

# --- Visualizza le prime 3 righe dei dati ---
df.head(3)

1. Il dataset contiene 178 campioni e 13 feature.
--------------------------------------------------
2. Ci sono 3 classi nel dataset.
--------------------------------------------------
3. I nomi delle feature sono:
   - alcohol
   - malic_acid
   - ash
   - alcalinity_of_ash
   - magnesium
   - total_phenols
   - flavanoids
   - nonflavanoid_phenols
   - proanthocyanins
   - color_intensity
   - hue
   - od280/od315_of_diluted_wines
   - proline
--------------------------------------------------


alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0

# Esercizio 1.2
 - 500 campioni
 - 8 feature totali (4 informative, 2 ridondanti)
 - 3 classi
 - 2 cluster per classe
 Poi visualizza le statistiche di base del dataset creato


In [249]:
# Parametri per la generazione del dataset
n_samples = 500      
n_features = 8       
n_informative = 4    
n_redundant = 2       
n_classes = 3         
n_clusters_per_class = 2 

# Generazione del dataset
X, y = make_classification(
    n_samples=n_samples,
    n_features=n_features,
    n_informative=n_informative,
    n_redundant=n_redundant,
    n_classes=n_classes,
    n_clusters_per_class=n_clusters_per_class,
    random_state=42 
)

In [250]:
# Diamo nomi generici alle colonne delle feature
feature_names = [f'feature_{i+1}' for i in range(n_features)]
df = pd.DataFrame(X, columns=feature_names)
df['class'] = y

print("Dataset sintetico creato con successo!")
print(f"Dimensioni del DataFrame: {df.shape}")

Dataset sintetico creato con successo!
Dimensioni del DataFrame: (500, 9)


In [251]:
print("Statistiche di base del dataset generato:")
basic_stats = df.describe()

display(basic_stats)

Statistiche di base del dataset generato:


feature_1   feature_2   feature_3   feature_4   feature_5   feature_6  \
count  500.000000  500.000000  500.000000  500.000000  500.000000  500.000000   
mean     0.027704    0.063435    0.334700    0.092092   -0.040661   -0.305071   
std      1.648191    1.016804    1.567857    1.530861    1.457437    1.515622   
min     -4.966780   -3.386814   -3.715971   -3.970294   -5.170028   -4.756125   
25%     -1.151050   -0.628710   -0.715418   -0.942849   -1.112372   -1.324587   
50%      0.079064    0.061462    0.486138    0.146235   -0.082120   -0.216098   
75%      1.276206    0.757136    1.403241    1.157614    0.994071    0.807073   
max      5.024299    2.562528    5.521261    5.435939    4.058305    4.392493   

        feature_7   feature_8       class  
count  500.000000  500.000000  500.000000  
mean     0.388791    0.050137    0.996000  
std      1.694436    0.994684    0.815668  
min     -5.132732   -2.924925    0.000000  
25%     -0.893219   -0.638717    0.000000  
50%      0.268277    0.095285    1.000000  
75%      1.661729    0.737795    2.000000  
max      5.105084    3.495878    2.000000

# Esercizio 1.3
-  Carica il dataset Diabetes
-  Crea un dataset sintetico di regressione con le stesse dimensioni
-  Confronta le statistiche (media, std, range) delle feature

In [252]:
# 1. Carica il dataset Diabetes
diabetes_data = load_diabetes()
df_diabetes = pd.DataFrame(diabetes_data.data, columns=diabetes_data.feature_names)

# Ottieni le dimensioni per il dataset sintetico
n_samples, n_features = df_diabetes.shape

print("Dataset Diabetes caricato.")
print(f"Dimensioni: {n_samples} campioni, {n_features} feature.")
print("Nomi delle feature:", df_diabetes.columns.to_list())

Dataset Diabetes caricato.
Dimensioni: 442 campioni, 10 feature.
Nomi delle feature: ['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']


In [253]:
# 2. Crea un dataset sintetico con le stesse dimensioni
X_synth, y_synth = make_regression(
    n_samples=n_samples,
    n_features=n_features,
    n_informative=5,  
    noise=10,         
    random_state=42   
)

df_synthetic = pd.DataFrame(X_synth, columns=df_diabetes.columns)

print("Dataset sintetico creato con successo.")
print(f"Dimensioni: {df_synthetic.shape[0]} campioni, {df_synthetic.shape[1]} feature.")

Dataset sintetico creato con successo.
Dimensioni: 442 campioni, 10 feature.


In [254]:
# .T traspone la tabella per una migliore leggibilità
stats_diabetes = df_diabetes.describe().T  
stats_synthetic = df_synthetic.describe().T

stats_diabetes['range'] = stats_diabetes['max'] - stats_diabetes['min']
stats_synthetic['range'] = stats_synthetic['max'] - stats_synthetic['min']

# Unione delle statistiche per un confronto
# Aggiunta di un suffisso per distinguere le colonne
comparison_df = stats_diabetes[['mean', 'std', 'range']].join(
    stats_synthetic[['mean', 'std', 'range']],
    lsuffix='_diabetes',
    rsuffix='_synthetic'
)

print("Tabella di confronto delle statistiche principali:")
display(comparison_df)

Tabella di confronto delle statistiche principali:


mean_diabetes  std_diabetes  range_diabetes  mean_synthetic  \
age  -2.511817e-19      0.047619        0.217952       -0.047884   
sex   1.230790e-17      0.047619        0.095322        0.085763   
bmi  -2.245564e-16      0.047619        0.260831        0.014846   
bp   -4.797570e-17      0.047619        0.244442       -0.008875   
s1   -1.381499e-17      0.047619        0.280694       -0.005560   
s2    3.918434e-17      0.047619        0.314401       -0.045088   
s3   -5.777179e-18      0.047619        0.283486        0.018350   
s4   -9.042540e-18      0.047619        0.261629        0.058464   
s5    9.293722e-17      0.047619        0.259694       -0.007454   
s6    1.130318e-17      0.047619        0.273379        0.007673   

     std_synthetic  range_synthetic  
age       1.004919         5.947485  
sex       0.953936         6.724994  
bmi       0.942739         5.230165  
bp        1.027511         5.663856  
s1        1.024488         6.393324  
s2        0.997685         5.440762  
s3        1.054779         5.925648  
s4        0.931485         6.086513  
s5        0.995153         6.128885  
s6        1.035117         6.556968

## Parte 2

# Esercizio 2.1
- Confronta i risultati mostrando media e deviazione standard prima e dopo

In [255]:

wine_data = load_wine()
# Crea un DataFrame per una facile manipolazione
df = pd.DataFrame(wine_data.data, columns=wine_data.feature_names)

print("Dataset Wine caricato con successo.")
df.head()


Dataset Wine caricato con successo.


alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0  
3                          3.45   1480.0  
4                          2.93    735.0

In [256]:
#Statistiche prima dello scaling
stats_prima = df.describe().T[['mean', 'std']]

print("Statistiche delle feature prima dello scaling:")
display(stats_prima)

Statistiche delle feature prima dello scaling:


mean         std
alcohol                        13.000618    0.811827
malic_acid                      2.336348    1.117146
ash                             2.366517    0.274344
alcalinity_of_ash              19.494944    3.339564
magnesium                      99.741573   14.282484
total_phenols                   2.295112    0.625851
flavanoids                      2.029270    0.998859
nonflavanoid_phenols            0.361854    0.124453
proanthocyanins                 1.590899    0.572359
color_intensity                 5.058090    2.318286
hue                             0.957449    0.228572
od280/od315_of_diluted_wines    2.611685    0.709990
proline                       746.893258  314.907474

- Applicazione Standard Scaler

In [257]:

scaler_standard = StandardScaler()
df_standard_scaled = pd.DataFrame(scaler_standard.fit_transform(df), columns=df.columns)

stats_standard = df_standard_scaled.describe().T[['mean', 'std']]

print("Statistiche dopo l'applicazione di StandardScaler:")
display(stats_standard)

Statistiche dopo l'applicazione di StandardScaler:


mean       std
alcohol                       7.943708e-15  1.002821
malic_acid                    3.592632e-16  1.002821
ash                          -4.066660e-15  1.002821
alcalinity_of_ash            -7.983626e-17  1.002821
magnesium                    -7.983626e-17  1.002821
total_phenols                -3.991813e-17  1.002821
flavanoids                    9.979533e-16  1.002821
nonflavanoid_phenols         -5.588538e-16  1.002821
proanthocyanins              -1.656602e-15  1.002821
color_intensity              -3.442939e-16  1.002821
hue                           1.636643e-15  1.002821
od280/od315_of_diluted_wines  2.235415e-15  1.002821
proline                      -1.197544e-16  1.002821

- Applicazione del MinMaxScaler

In [258]:
scaler_minmax = MinMaxScaler()
df_minmax_scaled = pd.DataFrame(scaler_minmax.fit_transform(df), columns=df.columns)

stats_minmax = df_minmax_scaled.describe().T[['mean', 'std', 'min', 'max']]

print("Statistiche dopo l'applicazione di MinMaxScaler:")
display(stats_minmax)

Statistiche dopo l'applicazione di MinMaxScaler:


mean       std  min  max
alcohol                       0.518584  0.213639  0.0  1.0
malic_acid                    0.315484  0.220780  0.0  1.0
ash                           0.538244  0.146708  0.0  1.0
alcalinity_of_ash             0.458502  0.172142  0.0  1.0
magnesium                     0.323278  0.155244  0.0  1.0
total_phenols                 0.453487  0.215811  0.0  1.0
flavanoids                    0.356386  0.210730  0.0  1.0
nonflavanoid_phenols          0.437460  0.234818  0.0  1.0
proanthocyanins               0.372523  0.180555  0.0  1.0
color_intensity               0.322363  0.197806  0.0  1.0
hue                           0.388170  0.185831  0.0  1.0
od280/od315_of_diluted_wines  0.491460  0.260070  0.0  1.0
proline                       0.334446  0.224613  0.0  1.0

# Esercizio 2.2: 
- Crea un array con valori mancanti (NaN) in posizioni casuali
- Applica SimpleImputer con strategie: 'mean', 'median', 'most_frequent'
- Confronta i risultati

In [ ]:
X_originale = np.array([
    [1, 8, 7, 5, 1, 1, 9, 2, 4, 6],
    [5, 2, 2, 5, 8, 9, 3, 2, 1, 5]
], dtype=float) 


X_mancante = X_originale.copy()
X_mancante[0, 2] = np.nan 
X_mancante[0, 5] = np.nan 
X_mancante[1, 6] = np.nan 
X_mancante[1, 9] = np.nan 

print("Array originale con valori mancanti (NaN):")
print(X_mancante)

Array originale con valori mancanti (NaN):
[[ 1.  8. nan  5.  1. nan  9.  2.  4.  6.]
 [ 5.  2.  2.  5.  8.  9. nan  2.  1. nan]]


In [260]:
# 2. Applica SimpleImputer con tre strategie diverse

# Strategia: 'mean' (media)
# Sostituisce i NaN con la media dei valori presenti nella colonna
imputer_mean = SimpleImputer(strategy='mean')
X_imputato_mean = imputer_mean.fit_transform(X_mancante)

# Strategia: 'median' (mediana)
# Sostituisce i NaN con la mediana dei valori presenti nella colonna
imputer_median = SimpleImputer(strategy='median')
X_imputato_median = imputer_median.fit_transform(X_mancante)

# Strategia: 'most_frequent' (valore più frequente)
# Sostituisce i NaN con il valore più comune nella colonna
imputer_most_frequent = SimpleImputer(strategy='most_frequent')
X_imputato_most_frequent = imputer_most_frequent.fit_transform(X_mancante)

In [261]:
# 3. Confronta i risultati

print("--- CONFRONTO DEI RISULTATI ---")
print("\nArray originale con valori mancanti:")
print(X_mancante)

print("\nRisultato con strategia 'mean':")
print(X_imputato_mean)

print("\nRisultato con strategia 'median':")
print(X_imputato_median)

print("\nRisultato con strategia 'most_frequent':")
print(X_imputato_most_frequent)

--- CONFRONTO DEI RISULTATI ---

Array originale con valori mancanti:
[[ 1.  8. nan  5.  1. nan  9.  2.  4.  6.]
 [ 5.  2.  2.  5.  8.  9. nan  2.  1. nan]]

Risultato con strategia 'mean':
[[1. 8. 2. 5. 1. 9. 9. 2. 4. 6.]
 [5. 2. 2. 5. 8. 9. 9. 2. 1. 6.]]

Risultato con strategia 'median':
[[1. 8. 2. 5. 1. 9. 9. 2. 4. 6.]
 [5. 2. 2. 5. 8. 9. 9. 2. 1. 6.]]

Risultato con strategia 'most_frequent':
[[1. 8. 2. 5. 1. 9. 9. 2. 4. 6.]
 [5. 2. 2. 5. 8. 9. 9. 2. 1. 6.]]
